sudo: required
services:
    - docker

before_install:
    - docker build -t nileshb83/dokcer-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nileshb83/dokcer-react npm run test -- --coverage
