sudo: required
services:
    - docker

before_install:
    - docker build -t nileshb83/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nileshb83/docker-react npm run test -- --coverage
